name: CI_TFSFinal
on:
  push:
    branches: [ origin ]
  pull_request:
    branches: [ origin ]
  workflow_dispatch:
jobs:
  buildDockerArtifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tfsfinalback:0.0.1

      - name: Deploy to Test Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo docker pull daniel0k/tfsfinalback:0.0.1
            docker stop TFSBack
            docker rm TFSBack
            sudo docker run --name=TFSBack -d -p 3000:3000 daniel0k/tfsfinalback:0.0.1